[package]
name = "cg-tg-rcore-tutorial-t3l2"
description = "A learning-oriented rCore Tutorial chapter 2 kernel crate that assembles a moving Tangram OS logo through batch user programs and trap-driven syscalls."
version = "0.0.0"
edition = "2024"
authors = ["YdrMaster <ydrml@hotmail.com>","Yifan Wang<w-yf22@mails.tsinghua.edu.cn>","Yu Chen <yuchen@tsinghua.edu.cn>"]
repository = "https://github.com/cg24-THU/tg-rcore-tutorial"
homepage = "https://github.com/cg24-THU/tg-rcore-tutorial/tree/test/tg-rcore-tutorial-ch2"
documentation = "https://docs.rs/cg-tg-rcore-tutorial-t3l2"
license = "GPL-3.0"
readme = "README.md"
keywords = ["ai", "ai4ose", "kernel", "learning", "os"]
categories = ["os", "embedded", "no-std"]
rust-version = "1.85"
include = [
    ".cargo/config.toml",
    "Cargo.toml",
    "Makefile",
    "README.md",
    "build.rs",
    "docs/**",
    "rust-toolchain.toml",
    "src/**",
    "test.sh",
    "user-src/**",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "cg-tg-rcore-tutorial-t3l2"
path = "src/main.rs"
test = false
bench = false

[dependencies]
riscv = "0.10.1"
spin = "0.9"
virtio-drivers = "0.1.0"

tg-sbi = { package = "tg-rcore-tutorial-sbi", path = "../tg-rcore-tutorial-sbi", version = "0.4.8", features = ["nobios"] }
tg-linker = { package = "tg-rcore-tutorial-linker", path = "../tg-rcore-tutorial-linker", version = "0.4.8" }
tg-console = { package = "tg-rcore-tutorial-console", path = "../tg-rcore-tutorial-console", version = "0.4.8" }
tg-kernel-context = { package = "tg-rcore-tutorial-kernel-context", path = "../tg-rcore-tutorial-kernel-context", version = "0.4.8" }
tg-syscall = { package = "tg-rcore-tutorial-syscall", path = "../tg-rcore-tutorial-syscall", version = "0.4.8", features = ["kernel"] }

[build-dependencies]
tg-linker = { package = "tg-rcore-tutorial-linker", path = "../tg-rcore-tutorial-linker", version = "0.4.8" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[package.metadata.docs.rs]
targets = ["riscv64gc-unknown-none-elf"]
