run:
	RUSTUP_TOOLCHAIN=stable cargo run

run-exercise:
	RUSTUP_TOOLCHAIN=stable cargo run --features exercise

check:
	RUSTUP_TOOLCHAIN=stable cargo check

build:
	RUSTUP_TOOLCHAIN=stable cargo build

test:
	bash ./test.sh all

package:
	RUSTUP_TOOLCHAIN=stable cargo package

publish-dry-run:
	RUSTUP_TOOLCHAIN=stable cargo publish --dry-run
