run:
	RUSTUP_TOOLCHAIN=stable cargo run

run-exercise:
	RUSTUP_TOOLCHAIN=stable cargo run --features exercise

run-ch6:
	CG_TG_CASE_SET=ch6 RUSTUP_TOOLCHAIN=stable cargo run --bin ch6_smp

check:
	RUSTUP_TOOLCHAIN=stable cargo check

build:
	RUSTUP_TOOLCHAIN=stable cargo build

package:
	RUSTUP_TOOLCHAIN=stable cargo package

publish-dry-run:
	RUSTUP_TOOLCHAIN=stable cargo publish --dry-run
