run:
	RUSTUP_TOOLCHAIN=stable cargo run

run-ch1:
	RUSTUP_TOOLCHAIN=stable cargo run --bin ch1_smp

check:
	RUSTUP_TOOLCHAIN=stable cargo check

build:
	RUSTUP_TOOLCHAIN=stable cargo build

package:
	RUSTUP_TOOLCHAIN=stable cargo package

publish-dry-run:
	RUSTUP_TOOLCHAIN=stable cargo publish --dry-run
